### ISSUE TITLE
Macros fails when case class has 23 values

### ISSUE THREAD

**Issue by michalbogacz** [ReactiveMongo/ReactiveMongo-BSON#205]
### Actual Behavior

Compilation of
```
    case class TestCaseClass(
      string1: String,
      string2: String,
      string3: String,
      string4: String,
      string5: String,
      string6: String,
      string7: String,
      string8: String,
      string9: String,
      string10: String,
      string11: String,
      string12: String,
      string13: String,
      string14: String,
      string15: String,
      string16: String,
      string17: String,
      string18: String,
      string19: String,
      string20: String,
      string21: String,
      string22: String,
      string23: String
    )

    implicit val handler = Macros.handler[TestCaseClass]
```
Fails with message
```
No matching apply/unapply found: com.test.TestCaseClass
[error]     implicit val hander = Macros.handler[TestCaseClass]
```

### Expected Behavior

Handler should be created.

Is there any workaround for this? (other than changing case class)

**Comment by cchantep** [comment]
Hi,

Short answer: no; Nothing specific to these macros, as Scala case class > 22 is degraged with extractor not generated by the compiler.
Long answer, ending with such case class, is a symptom of design issue.

Also, as indicated in the [guidelines](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), please use the [MailingList](https://groups.google.com/g/reactivemongo) to ask question/for help, not this issue tracker.

Best regards
